<!-- ---
reviewed_on: "2024-12-16"
--- -->

# NumPy

NumPy (Numerical Python) is an open source Python library that is widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional `ndarray`, and a large library of functions that operate efficiently on these data structures.

## Installation

### Using `pip`

```BASH
pip install numpy
```

### Using Anaconda

```BASH
conda install numpy
```

> In the Anaconda prompt.

## Usage example

In [1]:
import numpy as np

### Array creation

In [2]:
python_array = [[1, 2, 3],[4, 5, 6]]
np_array = np.array(python_array)
print(np_array.shape)
print(np_array[0, 0], np_array[0, 1], np_array[1, 0])

(2, 3)
1 2 4


In [3]:
np_array = np.zeros((2, 2))
print(np_array)

np_array = np.ones((2, 2))
print(np_array)

np_array = np.full((2, 2), 7)
print(np_array)

np_array = np.eye(5)
print(np_array)

np_array = np.random.random((3, 3))
print(np_array)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.18474369 0.39483236 0.31454896]
 [0.95088214 0.87632849 0.87706632]
 [0.00825671 0.04098077 0.51259238]]


In [2]:
n = 15

lin_array = np.linspace(0, 10, n)
log_array = np.logspace(0, 10, n)
print(lin_array, '\n', log_array)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ] 
 [1.00000000e+00 5.17947468e+00 2.68269580e+01 1.38949549e+02
 7.19685673e+02 3.72759372e+03 1.93069773e+04 1.00000000e+05
 5.17947468e+05 2.68269580e+06 1.38949549e+07 7.19685673e+07
 3.72759372e+08 1.93069773e+09 1.00000000e+10]


#### Comparation

In [2]:
import time

In [11]:
size = pow(10, 8)

##### Ones

In [12]:
start = time.time()
python_array = [0 for _ in range(size)]
stop = time.time()

print(stop - start)

6.795980453491211


In [15]:
start = time.time()
np_array = np.zeros(size)
stop = time.time()

print(stop - start)

0.025355815887451172


##### Range

In [16]:
start = time.time()
python_array = list(range(size))
stop = time.time()

print(stop - start)

2.281742572784424


In [19]:
start = time.time()
np_array = np.arange(size)
stop = time.time()

print(stop - start)

0.13424181938171387


### Array access

In [30]:
np_array = np.random.randint(0, 100, 10)

print(np_array)
print("Fifth element", np_array[4])
print("Before the fifth element (excluding it)", np_array[:4])
print("After the fifth element (including it)", np_array[4:])
print("From the third element (including it) until the eight (excluding it)", np_array[2:7])
print("Last element", np_array[-1])
print("Odd position elements", np_array[1::2])
print("Reversed array". np_array[::-1])

[94 44 96 14 63 94 46  9 41 93]
Fifth element 63
Before the fifth element (excluding it) [94 44 96 14]
After the fifth element (including it) [63 94 46  9 41 93]
From the third element (including it) until the eight (excluding it) [96 14 63 94 46]
Last element 93
Odd position elements [44 14 94  9 93]


> As it can be see, it is the same notation as Python.

---

In [4]:
np_array = np.array([
						[1, 2, 3, 4],
						[5, 6, 7, 8],
						[9, 10, 11, 12]
					])

a = np_array[:2, 1:3] # [rows, colums]
print(a)
a[0, 0] = 15 # Modifying the slice is the same as modifying the original
print(np_array)

[[2 3]
 [6 7]]
[[ 1 15  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
np_array = np.array([
						[1, 2, 3, 4],
						[5, 6, 7, 8],
						[9, 10, 11, 12]
					])

row_1 = np_array[1, :]
print(row_1, row_1.shape)

row_1 = np_array[1:2, :]
print(row_1, row_1.shape)

row_1 = np_array[[1], :]
print(row_1, row_1.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [8]:
np_array = np.array([
						[1, 2],
						[3, 4],
						[5, 6]
					])

bool_arary = np_array > 2
print(bool_arary)

true_elements = np_array[bool_arary]
print(true_elements)

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [4]:
x = np.array([
				[1, 2],
				[3, 4]
			], dtype=np.float64)

y = np.array([
				[4, 5],
				[6, 7]
			], dtype=np.float64)

In [5]:
print(x + y, '\n',np.add(x, y))

[[ 5.  7.]
 [ 9. 11.]] 
 [[ 5.  7.]
 [ 9. 11.]]


In [10]:
print(x - y, '\n', np.subtract(x, y))

[[-3. -3.]
 [-3. -3.]] [[-3. -3.]
 [-3. -3.]]


In [ ]:
print(x / y, '\n', np.divide(x, y))

In [ ]:
print(np.sqrt(x))

### Reshaping a matrix

In [6]:
np_array = np.random.randint(0, 100, size=(6, 5))

new_array = np_array.reshape(5, 6)
print(np_array, '\n', new_array)

new_array = np_array.reshape(3, 10)
print(np_array, '\n', new_array)

new_array = np_array.reshape(15, -1)
print(np_array, '\n', new_array)

[[30 28 21 36 37]
 [43 61 66 81 80]
 [46 61 79 46  1]
 [ 6 66 93 76 30]
 [ 0 23 70 23 73]
 [56  9 39 32 28]] 
 [[30 28 21 36 37 43]
 [61 66 81 80 46 61]
 [79 46  1  6 66 93]
 [76 30  0 23 70 23]
 [73 56  9 39 32 28]]
[[30 28 21 36 37]
 [43 61 66 81 80]
 [46 61 79 46  1]
 [ 6 66 93 76 30]
 [ 0 23 70 23 73]
 [56  9 39 32 28]] 
 [[30 28 21 36 37 43 61 66 81 80]
 [46 61 79 46  1  6 66 93 76 30]
 [ 0 23 70 23 73 56  9 39 32 28]]
[[30 28 21 36 37]
 [43 61 66 81 80]
 [46 61 79 46  1]
 [ 6 66 93 76 30]
 [ 0 23 70 23 73]
 [56  9 39 32 28]] 
 [[30 28]
 [21 36]
 [37 43]
 [61 66]
 [81 80]
 [46 61]
 [79 46]
 [ 1  6]
 [66 93]
 [76 30]
 [ 0 23]
 [70 23]
 [73 56]
 [ 9 39]
 [32 28]]


### Dot product

Is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors), and returns a single number.

$$
a = [a_1,a_2,\dots,a_n] \quad b = [b_1,b_2,\dots,b_n] \\[10 pt]

a \cdot b = \sum_{ i = 1 }^n { a_i * b_i }
$$

In [11]:
v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w), np.dot(v, w))

219


When this is applied to matrices, it returns the matrix multiplication.

In [13]:
print(np.dot(x, y), x @ y)

[[16. 19.]
 [36. 43.]] [[16. 19.]
 [36. 43.]]


---

### Transpose

In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix $A$ by producing another matrix, often denoted by $A^T$. 

In [14]:
print(x, x.T)

[[1. 2.]
 [3. 4.]] [[1. 3.]
 [2. 4.]]


### Solving a equation system problem

$$
\begin{align*}
& 6 x_1 & - & 3 x_2 & + & x_3  & = & 11 \\
& x_1   & - & 7 x_2 & + & x_3   & = & 10 \\
& 2 x_1 & + & x_2   & - & 8 x_3 & = & -15 \\
\end{align*}
$$

In [10]:
A = np.array([
				[6, -3, 1],
				[1, -7, 1],
				[2, 1, -8]
			])

results = np.array([11, 10, -15])

x = results.reshape(3, 1)

#### Using the inverse matrix

$$
A x = b \\[10 pt]

A^{ -1 } A x = A^{ -1 } b \quad I x = A^{ -1 } b \quad x = A^{ -1 } b 
$$

In [11]:
inversed_A = np.linalg.inv(A)
solution = np.dot(inversed_A, x)
print(solution)

[[ 1.]
 [-1.]
 [ 2.]]


#### Using a NumPy built-in method

In [10]:
solution = np.linalg.solve(A, x)
print(solution)

[[ 1.]
 [-1.]
 [ 2.]]
