<!-- ---
reviewed_on: "2024-12-16"
--- -->

# Iterative methods for solving linear equation systems

In [2]:
import numpy as np

## Gradient descent

In [37]:
def gradient_descent(A, b, x_0, delta, iterations=100):
	x = x_0
	for _ in range(iterations):
		r = b - np.matmul(A, x)
		r_t = np.transpose(r)
		alpha = np.dot(r_t, r) / \
				np.dot(r_t, np.matmul(A, r))
		x = x + alpha * r

		if np.linalg.norm(r) < delta:
			return x

	else:
		return x # raise ValueError("Gradient descent did not converge")

In [38]:
A = np.array([
	[3, -2],
	[-2, 4]
])

b = np.array([
	4,
	8
])

x_0 = np.array([
	1,
	1
])

gradient_descent(A, b, x_0, 1e-08, 10000)

array([4., 4.])

## Conjugate gradient

In [17]:
def conjugate_gradient(A, b, x_0, delta, iterations=100):
	x = x_0
	r = b - np.matmul(A, x)
	r_t = np.transpose(r)
	p = r
	p_t = r_t
	alpha = np.dot(r_t, p) / \
				np.dot(p_t, np.matmul(A, p))

	for _ in range(iterations):
		x = x + alpha * p

		r_previous = r

		r = b - np.matmul(A, x)
		r_t = np.transpose(r)

		p_previous = p
		p_previous_t = np.transpose(p)

		betha = np.dot(p_previous_t, np.matmul(A, r_previous)) / \
				np.dot(p_previous_t, np.matmul(A, p_previous))

		p = r + betha * r_previous
		p_t = np.transpose(p)

		alpha = np.dot(r_t, p) / \
				np.dot(p_t, np.matmul(A, p))

		if np.linalg.norm(r) < delta:
			return x

	else:
		return x # raise ValueError("conjugate descent did not converge")

In [18]:
A = np.array([
	[4, 1],
	[1, 3]
])

b = np.array([
	1,
	2
])

x_0 = np.array([
	0,
	0
])

conjugate_gradient(A, b, x_0, 1e-08, 10000)

array([0.09090909, 0.63636364])

## Jacobi

In [14]:
def Jacobi(A, b, x_0, delta, iterations=100):
	old_values = x_0
	equations = len(A) # = len(b) = len(x_0)
	new_values = [None] * equations

	for _ in range(iterations):
		for i in range(equations):
			sigma = 0

			for j in range(equations):
				if i == j:
					continue
				else:
					sigma += A[i][j] * old_values[j]

			new_values[i] = 1 / A[i][i] * (b[i] - sigma)

		are_tolerated_values = True
		for i in range(new_values):
			error = abs((new_values[i] - old_values[i]) / new_values[i])

			if error > delta:
				are_tolerated_values =  False
				break

		if are_tolerated_values:
			return new_values

		old_values = new_values

	return new_values

In [19]:
A = np.array([
	[4, 1],
	[1, 3]
])

b = np.array([
	1,
	2
])

x_0 = np.array([
	0,
	0
])

Jacobi(A, b, x_0, 0.1, 1000)

[0.09090909090909091, 0.6363636363636364]

## Gauss-Seidel

In [57]:
def GaussSeidel(A, b, x_0, delta, iterations=100):
	values = x_0
	equations = len(A) # = len(b) = len(x_0)

	for _ in range(iterations):
		are_tolerated_values = True
		for i in range(equations):
			sigma_1 = 0
			sigma_2 = 0

			for j in range(0, i):
				sigma_1 += A[i][j] * values[j]

			for j in range(i + 1, equations):
				sigma_2 += A[i][j] * values[j]

			new_value = 1 / A[i][i] * (b[i] - sigma_1 - sigma_2)
			error = abs((new_value - values[i]) / new_value)

			if error > delta:
				are_tolerated_values =  False

			values[i] = new_value

		if are_tolerated_values:
			return values

	return values

In [59]:
A = np.array([
	[4, 1],
	[1, 3]
])

b = np.array([
	1,
	2
])

x_0 = np.array([
	0.0,
	0.0
])

GaussSeidel(A, b, x_0, 0.1, 1000)

array([0.09090909, 0.63636364])